### ISSUE TITLE
wikdict.svg logo issues (and ideas for easy fixes)

### ISSUE THREAD

**Issue by hartwork** [karlb/wikdict-web#13]
Hi @karlb,

I noticed that the [`wikdict.svg` logo](https://github.com/karlb/wikdict-web/blob/master/static/img/wikdict.svg) is rendered rather unfortunately (e.g. in desktop Chromium, screenshots below), especially with rather unsharp edges. So I had a closer look at the file in Inkscape…

What I found was that
- the black "W" has a _dashed green line_ around it (when zooming in) that causes the rendering issues, and that
- the speech bubble has rather _non-round corners_  (when zooming in).

Here's a picture to show both issues up close:
![wikdict_demo](https://user-images.githubusercontent.com/1577132/141137789-621fa91a-b190-4854-ada5-7fd51d8eb432.png)

When quickly fixing former issue locally, the rendering goes from this…
![wikdict_unfixed](https://user-images.githubusercontent.com/1577132/141136721-791fcdef-979f-42c6-8790-a6481a768297.png)
…to this…
![wikdict_fixed](https://user-images.githubusercontent.com/1577132/141136755-ad8009c7-210f-4b4c-aeae-a62c6c0f65f7.png)
already, which is significantly sharper.

Please let me know what your requirements are for a pull request, or if this is something you'd rather take over yourself.

Best, Sebastian

**Comment by karlb** [comment]
Well spotted. I lost my original SVG somewhere along the way and just traced a bitmap to get a placeholder SVG. I have no idea where the green line comes from, though.

There are no specific requirements, except that the logo must look similar. PR welcome!
