### ISSUE TITLE
Language bugs in label "Enter a word in <language_from> or <language_to>"?

### ISSUE THREAD

**Issue by hartwork** [karlb/wikdict-web#2]
Hi @karlb, thanks for your star on [git-delete-merged-branches](https://github.com/hartwork/git-delete-merged-branches) :pray: :tada: 

I noticed that on https://www.wikdict.com/ below the search box there is a sentence `Enter a word in <language_from> or <language_to>` with language names appearing
- in uppercase some of the time and in lowercase the rest of the time
- in their native spelling (e.g. "ελληνικά") rather than their English name (e.g. Greek).

What I currently see:
```
Enter a word in English or français
Enter a word in Deutsch or ελληνικά 
Enter a word in italiano or polski
```

What I'd expect:
```
Enter a word in English or French
Enter a word in German or Greek
Enter a word in Italian or Polish
```

Appending `| capitalize` at… https://github.com/karlb/wikdict-web/blob/7e035326da99a1198aa4e8a19ff5fdc8194cc85e/wikdict_web/templates/lookup.html#L79 …would only address the uppercase part of the issue, and also keep me wondering if varying letter case in `language_names` is a bug or a feature. What do you think?

Best, Sebastian

**Comment by karlb** [comment]
Hi Sebastian, great to hear from you!

At some point, I wanted to offer the WikDict UI in different languages (would still be nice, just not for up on my todo list) and for that I would need a list of all languages in all available UI languages. I didn't find a good data source for that, so I just put in all language names in their on language.

You're right that this is a bit awkward. I'll change that to the English names and that should solve the capitalization as a result. And while I'm at it, I can also add Unicode country flags to each of the languages.

Thanks for your feedback and looking forward to seeing you again some time (maybe at a Berlin Hack and Tell?)!

**Comment by hartwork** [comment]
Hi @karlb , good to know that [Berlin Hack & Tell](https://berlinhackandtell.rocks/) is going again. I'm still rather shy of indoor stuff despite double vaccination, will see.

I think all-English by default would be nice. I imagine adding a new (first?) column to file [`wikdict_web/languages/languages.tsv`](https://github.com/hartwork/wikdict-web/blob/master/wikdict_web/languages/languages.tsv) with the English display name, e.g. "Greek" rather than current "Greek (modern)" in column 2.
Is that the approach you would take as well? Would you want you or me to make a pull request?

Flags will be nice to have, sure.

**Comment by karlb** [comment]
I have something in the works and am currently trying to use data from WikiData, since that will also be a good data source for additional information (e.g. name of the language in other languages). I'll probably push a first version later today.

**Comment by karlb** [comment]
The `Enter a word in <language_from> or <language_to>` is updated to the English names and flags are added to the results page.

TODO:
- [ ] Unify new data set with old `language_names` dict
- [ ] Decide where we want to use the native language names and where the English ones

**Comment by hartwork** [comment]
> The `Enter a word in <language_from> or <language_to>` is updated to the English names and flags are added to the results page.

Very nice, thank you!

For self-reference, these two commits on `master` are related:
- 130504b5838fc929a2a50e6de73acb31090a18c9 — *Add language data from WikiData*
- d18f9ef372a705dda63edd04a7b01e19a3051108 — *Use English language names in call to action*

> * [ ]  Decide where we want to use the native language names and where the English ones

My vote for English everywhere before fully going multilingual. It helps everyone but people who don't know English,

**Comment by hartwork** [comment]
Hi @karlb I came across this ticket as "still open" on my personalized view on https://github.com/issues. With regard to my original report above, I consider it fixed. Would you like to keep it open because of the potential follow-up todos mentioned at https://github.com/karlb/wikdict-web/issues/2#issuecomment-964406634 above or should we close the ticket as fixed?

**Comment by karlb** [comment]
I'll close this. I have https://github.com/karlb/wikdict-web/issues/26 for when I want to do larger changes with regards to language names.
