### ISSUE TITLE
Error "sqlite3.OperationalError: no such table: lang_pair" or how to fully initialize the database?

### ISSUE THREAD

**Issue by hartwork** [karlb/wikdict-web#5]
Hi @karlb ,

with #4 applied, I now run into exception `sqlite3.OperationalError: no such table: lang_pair` (full output further down). I did a `git grep lang_pair` but didn't find any instructions or code initializing that table. Are there instructions on how to go from an empty database to a fully functional database scheme? 

```console
# ./run_dev.sh 
WARNING: You are using pip version 21.1.1; however, version 21.3.1 is available.
You should consider upgrading via the '[..]/wikdict-web/venv/bin/python3 -m pip install --upgrade pip' command.
 * Serving Flask app 'wikdict_web' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 929-651-497
data/dict/wikdict.sqlite3
127.0.0.1 - - [09/Nov/2021 17:30:22] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "[..]/wikdict-web/venv/lib/python3.8/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "[..]/wikdict-web/venv/lib/python3.8/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "[..]/wikdict-web/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "[..]/wikdict-web/venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "[..]/wikdict-web/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "[..]/wikdict-web/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "[..]/wikdict-web/wikdict_web/__init__.py", line 58, in index
    return lookup.lookup(from_lang, to_lang)
  File "[..]/wikdict-web/wikdict_web/lookup.py", line 108, in lookup
    sum(lp.total_trans for lp in base.get_lang_pairs()) // 100000 / 10
  File "[..]/wikdict-web/wikdict_web/base.py", line 21, in f_with_timing
    result = f(*args, **kwargs)
  File "[..]/wikdict-web/wikdict_web/base.py", line 45, in get_lang_pairs
    return db_query('wikdict', """
  File "[..]/wikdict-web/wikdict_web/base.py", line 105, in db_query
    cur.execute(stmt, bind_params)
sqlite3.OperationalError: no such table: lang_pair
127.0.0.1 - - [09/Nov/2021 17:30:22] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [09/Nov/2021 17:30:22] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [09/Nov/2021 17:30:23] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [09/Nov/2021 17:30:23] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
```

Thanks in advance! :pray:

**Comment by karlb** [comment]
http://download.wikdict.com/dictionaries/sqlite/ is for people who want to use the data for different purposed than running wikdict-web. Wikdict-web needs a bit less normalized data, a few additional search indexes and the wikdict.sqlite db, which acts as an index of available language pairs.

I've made that data set available at http://download.wikdict.com/dictionaries/wdweb/. I should explain the differences somewhere to avoid confusion.

Let me know if there are any other stumbling blocks. It's rare that someone expresses interest in running the code themselves, so I didn't spend much time on making it easy to run, yet.

**Comment by hartwork** [comment]
> http://download.wikdict.com/dictionaries/sqlite/ is for people who want to use the data for different purposed than running wikdict-web. Wikdict-web needs a bit less normalized data, a few additional search indexes and the wikdict.sqlite db, which acts as an index of available language pairs.
> 
> I've made that data set available at http://download.wikdict.com/dictionaries/wdweb/.

I see! That new info enabled me to update my re-write of `download_dicts.sh` at #6. Please consider it ready for review.

> I should explain the differences somewhere to avoid confusion.

Yes please.

> Let me know if there are any other stumbling blocks.

My local dev copy seems running now, very nice. More (user relevant) bug reports upcoming…

> It's rare that someone expresses interest in running the code themselves, so I didn't spend much time on making it easy to run, yet.

I understand. Are there plans to make GitHub Actions run the test suite as CI for regression testing? Should I give a pull request a shot?

**Comment by karlb** [comment]
> Are there plans to make GitHub Actions run the test suite as CI for regression testing? Should I give a pull request a shot?

Yes, that would be welcome!

**Comment by hartwork** [comment]
> > Are there plans to make GitHub Actions run the test suite as CI for regression testing? Should I give a pull request a shot?
> 
> Yes, that would be welcome!

Here you go: #11 :smiley:

**Comment by karlb** [comment]
Remaining TODO:

- [x] I should explain the differences somewhere to avoid confusion.

**Comment by hartwork** [comment]
> * [ ]  I should explain the differences somewhere to avoid confusion.

Maybe at https://www.wikdict.com/page/download ?

**Comment by karlb** [comment]
I used Apache's FancyIndex to add a comment column to the directory listing at http://download.wikdict.com/dictionaries/. This way, users don't have to jump back and forth between the directory listing and the downloads explanation page.
